// Code generated by goagen v1.1.0, DO NOT EDIT.
//
// API "appengine": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/goadesign/examples/appengine/design
// --out=$(GOPATH)
// --version=v1.1.0

package app

// HelloHref returns the resource href.
func HelloHref() string {
	return "/hello"
}
