// Code generated by goagen v1.1.0, DO NOT EDIT.
//
// API "appengine": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/goadesign/examples/appengine/design
// --out=$(GOPATH)
// --version=v1.1.0

package app

// example MediaType (default view)
//
// Identifier: application/vnd.example+json; view=default
type Example struct {
	Message *string `form:"message,omitempty" json:"message,omitempty" xml:"message,omitempty"`
}
